ansible/README.rst, ansible/roles/deploy/defaults/main.yml, ansible/roles/deploy/handlers/main.yml, ansible/roles/deploy/tasks/main.yml, ansible/roles/deploy/templates/site.j2, ansible/run.yml
We'll obviously need to replace `beta.ceph.io` with `ceph.io` in the future but this is working for now with `ansible-playbook -e branch=develop run.yml`
=> Add ansible playbook to set up site

README.md
The ceph.io website as of now is not friendly towards those who would like to fix or at least to report mistakes on the website. This repo does not make it clear that it is for the new website under development and this creates confusion. See issue #3 for an example. It is safe to assume that the majority of people who would have otherwise reported or even fixed mistakes give up early in the process. This update provides direction for reports related to the current website and makes a statement about this repository's purpose as a home for the new website.
I still haven't found the information I require, so the following stubs in the README body must be updated:
In distributed projects, communication is _everything_. Please feel free to amend the proposed changes as you see fit. I only …
=> Update main README with user-friendly directions

README.md, package-lock.json, package.json, scripts/prebuild.js, src/_11ty/filters/formatDate.js, src/_11ty/filters/formatDateRange.js, src/_data/site.js, src/ja-JP/community/events/categories.html, src/ja-JP/community/events/events.json, src/ja-JP/community/events/index.html, src/ja-JP/news/press-releases/categories.html, src/ja-JP/news/press-releases/index.html, src/ja-JP/news/press-releases/press-releases.json, src/ja-JP/solutions/case-studies/case-studies.json, src/ja-JP/solutions/case-studies/categories.html, src/ja-JP/solutions/case-studies/index.html
Build script to automatically copy site pages from default locale site (`en-GB`) to supporting language sites (in this example, `ja-JP`).
Will automatically support all and any language sites, as defined by `locales`.
⚠️ Important to note: This means the `npm run build` action is strictly a build server/production environment script. Running this locally will copy files to local file system and we'll want to ensure these aren't committed to version control (as they're generated files, not source). Have added note to README.
PR includes some minor fixes to the various files/tags etc. that currently appear in the `ja-JP` site, to ensure they're on par with those in `en-GB`
=> Multilingual prebuild script

src/js/nav-secondary.js, src/js/off-canvas.js
Added addListener fallback for Safari <14 for both off-canvas.js and nav-secondary.js.
=> Refactored JS.

ansible/roles/deploy/templates/site.j2
I guess specifying `types { }` in a block higher than `http { }` overrides all of the default mime types so we need to manually include it at the same level again.
https://stackoverflow.com/a/20566966/6225562
=> ansible: Also include the default mime.types

ansible/roles/deploy/templates/site.j2
Following on from #104, it would be great if we could gzip `application/json` files. We'll have a few static JSON assets (search indices, etc.) which would benefit a lot from compression.
@djgalloway is this fair game/all we need to include?
Related, we currently have `text/javascript` included in our gzip types, but we set the `.mjs` MIME type to `application/javascript`. Based on [a little](https://github.com/google/WebFundamentals/issues/7549) [digging](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types), I've also updated this to `text/javascript` to ensure they're gzipped as intended. Shout if this isn't in line with your expectations.
=> Add `application/json` to gzip types, `mjs` MIME type update

src/_11ty/shortcodes/ArticleCard.js, src/_includes/components/case-study-card.njk, src/_includes/components/case-study-category-card.njk, src/_includes/components/event-card.njk, src/_includes/layouts/blog-post.njk, src/_includes/layouts/case-study.njk, src/_includes/layouts/event.njk, src/_includes/layouts/press-release.njk, src/css/base.document.css, src/css/base.media.css
- Richtext CSS so images are no wider than their native width but remain responsive
We have a global declaration for `img` that forces images to be 100% width of their parent container. I've removed this so where necessary we'll have to use the `w-full` utility class if we want an image to be 100% width of its container. It's been removed because as long as we have a global width declaration in the CSS, whether it be `auto` or `100%`, we won't be able to honor a width attribute on an `<img>`. It can be overriden by adding a `class` to the `img` but it's in the interest of keeping the markdown simple and not needing an awareness of our utility width classes.
Images that do appear in a `richtext` container will now be no wider than their native width but remain responsive, they will also …
=> Richtext image width

src/en/news/index.html
This PR adds a link to the subscription page
of the ceph-announcement mailing list. This link
is added to the placeholder button reading
"Subscribe to Ceph Announcements".
=> news/index.html: add subscribe link

src/en/developers/roadmap/index.md
This is the first PR that removes the marketing-
speak from the Roadmap page on ceph.io.
=> ceph.io/roadmap: cleaning up roadmap

src/en/developers/index.html
This is the first PR in a series of PRs that will
remove the marketing copy on the Developers page of the
ceph.io website. This PR:
- Links to the part of the Developer Guide that
explains how to make a PR to the Ceph Github
repo.
- Provides a link to the Github repo.
- Provides a link to the Ceph Issue Tracker (the
Redmine instance).
This provides the three basic tools that a potential
contributor will need to make a contribution to the
project.
Note: there will be more PRs to this file in the near
future after I consult with Sage. If you are not Sage
and you are reading this, don't think that this is the
only change that is being made to this page.
=> ceph.io/developers: rewriting marketing copy 1

src/en/developers/index.html
This PR:
- Links to the "Intro to Ceph" docs on docs.ceph.com.
- Updates the flavor text so that it refers to things that
are in the docs.
=> ceph.io/developers: update docs link

src/en/developers/contribute/index.html
This PR adds the Youtube video that explains how
to contribute to the Ceph community. I've put it here
in iframe html tags, but for some reason they don't work
within the website.
Maybe we can boot this to someone with greater understanding
of embedding video in this IA.
=> ceph.io/contribute: add contribute video

src/en/discover/index.html
This PR changes the header text from "Achieve
excellent performance, reliability and scalabitily
with Ceph." to "Ceph. The future of storage.".
I'm putting this in a PR now so that I can get it out
of the way. Fixing this is going to be a death of a
thousand cuts.
=> ceph.io/discover: change header text

src/en/news/index.html
This PR removes lorem ipsum text from a division containing
a button that links to the subscription page for ceph-announce.
I missed it the other day when I was adding the button.
=> ceph.io/news: removing lorem ipsum

src/en/developers/code/index.html
- Add link to Github repository
- Add link to Ceph tarballs
I think the leading (rhymes with "bedding", means
"space between one line of text and the next") between the
buttons and the headings is awful, but we'll return to fix
this later.
=> ceph.io/developers: rewrite "code" page

src/en/community/connect/index.html
I added tidy little divisions containing information
about "ceph-announce" and "ceph-users" to the "Community
Connect" page.
A future PR should probably put the "Ceph Users" division
in the right grid column, so that it looks tidy.
This is not a formatting PR. This is a content PR.
=> ceph.io/community -- added c-users and c-announce

.eleventy.js, src/_11ty/filters/cleanCardContent.js, src/_11ty/filters/cleanSearchRaw.js, src/_11ty/shortcodes/ArticleCard.js, src/_includes/components/event-card.njk, src/en/news/blog/search-output.html
- renamed cleanSearchOutput to cleanCardContent (it's more appropriate)
- added ¶ to list of punctuation
- removed a few characters from the punctuation for CardContent (let's keep an eye on this once more content goes in)
- replaced removeHtml with cleanCardContent in ArticleCard
Closes #153
=> Card content filtering

src/en/community/community.json
This PR adds five Ceph Month 2021 talks to the
"Tech Talks" subpage on the "Community" page,
and adds one video called "What's New in Pacific
Ceph Release". (All six things added are videos.)
=> ceph.io/community: add tech talks (1 of several)

src/en/users/index.html
This PR adds a link to the Ceph Public Telemetry
Dashboard to the Users page. It also links to the
documentation and cleans up the marketing-speak
that was present previously.
=> ceph.io/users: add telemetry dashboard

src/_data/i18n/index.js, src/_includes/layouts/listing-blog-post-categories.njk, src/_includes/layouts/listing-blog-posts.njk, src/_includes/layouts/listing-blog-search.njk, src/_includes/layouts/listing-case-studies.njk, src/_includes/layouts/listing-case-study-categories.njk, src/_includes/layouts/listing-event-categories.njk, src/_includes/layouts/listing-events.njk, src/_includes/layouts/listing-press-release-categories.njk, src/_includes/layouts/listing-press-releases.njk
- new i18n dictionary data
- category replacement for blog, case study, events and press releases
- blog search placeholder
- faux reset for collections with categories
Closes #139 #160
=> Minor UI updates

src/_includes/layouts/listing-blog-post-categories.njk, src/_includes/layouts/listing-blog-posts.njk, src/_includes/layouts/listing-press-release-categories.njk, src/_includes/layouts/listing-press-releases.njk
Excluded these categories `blog-post` and `press-release` as they are used for other functionality in the site.
Closes #162
=> Excluded irrelevant categories from blog posts and press releases

src/_includes/layouts/listing-blog-posts.njk
A very simple code tweak but worth checking it locally to make sure it's working as expected.
Newest blog posts should be appearing first.
Closes #128
=> Updated blog listing pagination order so newest appear first

scripts/search-index.js, src/_11ty/filters/cleanSearchRaw.js, src/_data/i18n/index.js, src/_includes/layouts/_base.njk, src/_includes/layouts/listing-blog-search.njk, src/css/utilities.display.css, src/en/news/blog/search-raw.html, src/js/search-output.js
- Remove `date` — not sure this field (given it's an ISO date it's not particularly searchable anyway)
- Use spaces instead of empty strings for `shortWords`, `unicode` and `punctuation` replacements. With these as empty strings we were seeing a lot of accidentally combined words in the index, especially in indexed code snippets (e.g. `radosopenpoolconst`). When these are properly separated, the quality of the index actually improves (more keywords), and the size greatly decreases due to compression.
- Removed the `dedupe`ing — this doesn't actually have a great impact on the final index size (due to compression), and may actually decrease the quality of results, as the pages with search terms frequently repeated should rank higher.
- Added `boost` param for `title` and `author` fields, …
=> Optimise search index

src/en/users/documentation/index.html
This PR adds text to the Users->Documentation
page.
=> doc/cephio: add users->documentation

src/en/discover/technology/index.html
* Resolves #204 by replacing all lorem ipsum text with additional details about Ceph's architecture
* Minor tweaks for consistency regarding heading capitalisation and link text
* Minor additions to opening section to explain in text the concept depicted in the architecture diagram (for a11y/text-only browsing goodness)
Signed-off-by: Wendy White <wendy@fishoutoforder.com>
=> Replaces all lorem ipsum text in Discover -> Technology

src/_data/social.js, src/_includes/components/site-footer.njk, src/_includes/layouts/_base.njk
Social share for Twitter have a subtle issue.
OG tag for `twitter:site` is expecting a twitter `@username` ([docs](https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started)), while the social share intent link (from Blog posts), is expecting just the username itself, no `@`. Including it leads to a double `@@`, and username is not linked appropriately:
This PR takes `@` usage out of `_data/social`, so we can explictly include it in templates only where needed.
`social.facebook` isn't being used yet, as far as I can see.
=> Use social usernames as is, adding @ where needed

.eleventy.js, src/_includes/layouts/_base.njk
Only update that arose based on browser testing (Edge, makes use of `manifest.json`, which wasn't present in `dist` files).
=> Cross-browser checks

.eleventy.js, package-lock.json, package.json, src/_11ty/transforms/html-minifier.js, src/en/community/team/index.html
- Installed html-minifier package
- Created transforms folder
- Fixed a few syntax issues on /community/team
Closes #220
=> HTML minify

src/en/news/blog/2021/v16-2-0-pacific-released/index.md
This PR corrects two misspelled instances of Anthony
D'Atri's name.
=> doc/releases: correct "Anthony D'Atri" spelling

src/_11ty/filters/formatDate.js, src/_11ty/filters/formatDateRange.js
We had this earmarked as something potentially needing attention, but hadn't realised the issue caused on the build server.
By ensuring we set `timeZone` (now in sync with [server timezone](https://github.com/ceph/ceph.io/issues/241#issuecomment-871685879)) to `UTC` and we `toUTCString()` any date coming to `formatDate()`, we ensure that dates avoid the off-by-one issue.
This should cover data-driven content dates across the site (blogs, press releases, events, tech talks).
Tested on branch deploy, and dates are as per data:
- https://241-utc-dates.ceph.io/en/news/blog/2021/v14-2-22-nautilus-released/
- https://241-utc-dates.ceph.io/en/community/tech-talks/
- https://241-utc-dates.ceph.io/en/community/events/2019/cephalocon-barcelona/
Closes #239
Fixes #241
=> Fix date formatting off-by-one bug

src/en/developers/index.html
* appends new 2-column section to the end of the developer resources page, for linking to downloadable Ceph how-tos / guides for beginners
* adds brief blurb for this section
* adds two links to Ceph guides in the new section
Signed-off by Wendy White <wendy@fishoutoforder.net>
=> Adds links to Ceph guides for beginngers to Developer resources page

src/en/developers/index.html
One section on the Developers page are not displaying quite correctly (not rendering on the page) due to line breaks added in #287. Commits to this branch are intended to fix this. 
Signed-off by Wendy White <wendy@fishoutoforder.net>
=> Addresses display issues on Developers page

src/en/community/events/2021/meetup-dach-2021-11-30/index.md, src/en/community/events/2022/cephalocon-portland/index.md
Adding the missing `title` field to frontmatter for the most recent to events, including the upcoming Cephalocon 2022.
This ensures that the event listing and event pages have proper headings in the page content, consistent with other previous events.
The specs for collections (like events, blog posts, etc.) are captured in their respective directories in the solution for more info: [Events README](https://github.com/ceph/ceph.io/tree/main/src/en/community/events#readme)
=> Add titles to Cephalocon and meetup

src/en/discover/technology/index.html
This updates a broken PDF link to a working PDF link.
On the page
https://ceph.com/en/discover/technology/
the following URL has been updated:
https://ceph.com/wp-content/uploads/2016/08/weil-rados-pdsw07.pdf returns 404 not found.
The above URL has been updated to the following URL:
https://ceph.com/assets/pdfs/weil-rados-pdsw07.pdf
I have not confirmed locally that this works, because my patience with
npm and nodejs has been exhausted.
=> doc: updating broken PDF link

src/en/developers/google-summer-of-code/index.md
The S3 test link needed "https://" before it to work properly.
Signed-off-by: Laura Flores <lflores@redhat.com>
=> en/developers/google-summer-of-code: fix broken link

src/en/news/blog/2017/new-luminous-cephfs-subtree-pinning/index.md
Fix the preformatted text by using 4 spaces instead of >.
=> blog/new-luminous-cephfs-subtree-pinning: fix preformatted text

src/en/news/blog/2022/red-hats-ceph-team-is-moving-to-ibm/index.md
Signed-off-by: Josh Durgin <jdurgin@redhat.com>
=> blog: Red Hat's Ceph team is moving to IBM

src/en/news/blog/2018/new-mimic-centralized-configuration-management/index.md
Refine the English in the blog post announcing the Central Config, which was introduced in Mimic.
=> doc/blog: refine Central Config blog post

src/en/community/events/2023/ceph-days-nyc/index.md
The current schedule lists Intel as my employer.  This is not accurate.
When we did the work, I worked for Intel
When it was merged, I worked for Solidigm (Intel spinoff) and the deck uses their template.
I now work for Index Exchange, who is not involved in this work.
Thus, I think it's best to not list an employer for me, to reduce confusion and so that Index
doesn't take issue with it.
Signed-off-by: Anthony D'Atri <anthonyeleven@users.noreply.github.com>
=> Ceph Day NYC 2023 correct AD employer

src/en/community/events/2023/cephalocon-amsterdam/index.md, src/en/news/blog/2023/cephalocon-2023-amsterdam/index.md
By popular demand, extend the Cephalocon 2023 CfP deadline by one week!
=> community/events: Cephalocon 2023 CfP extension

src/en/community/events/2023/ceph-days-nyc/index.md
Add a list of recommended hotels to the "Ceph Days NYC 2023" page.
Repair some ill-formed markdown.
=> community: add hotel list for Ceph Day 2023

src/en/community/meetups/index.html
Update the information about the Docubetter meetup, which was discontinued in 2021. Provide information about how to get in touch with me (Zac Dover), for all those who have questions or complaints or requests pertinent to Ceph documentation.
=> src/en/community/meetups.md - update Docubetter

src/en/news/blog/2023/reef-osds-per-nvme/index.md
Accidentally had the CPU graphs posted twice under the RSS memory usage section.
=> blog/2023: Fix URL for memory charts in reef-osds-per-nvme blog article

src/en/news/blog/2023/reef-osds-per-nvme/index.md
A user on reddit noticed some backwards "NVMes per OSDs" instead of "OSDs per NVMe" statements.  Also cleaned up a couple of sentences while fixing those statements.
=> blog/2023: Fix some typos in the reef-osds-per-nvme post

src/en/community/connect/index.html
The old one was supposed to never expire, but it seems to have anyway after ~9months. Here's a new one set to 'never expire'.
=> community: update slack invite link

src/en/developers/google-summer-of-code/index.md
Added a section in GSOC project regarding clang-tidy static analysis and integration into CI
=> src/en/developers/google-summer-of-code/index.md: add clang-tidy project

src/en/foundation/member-benefits/index.md
Ceph Days are usually locally organized outside of the purview of the Ceph Foundation so we cannot guarantee offering complimentary passes.
=> Member Benefits: Clarify complimentary passes

src/en/developers/google-summer-of-code/index.md
There were typos in emails, so fixed that,
also updated the project description.
=> google-summer-of-code/index.md: update Shaman project

src/en/developers/google-summer-of-code/index.md
* adding a ference to a gist holding the full description. and chaging scope to 175 hours.
* remove the "lunar time" project
=>  gsoc: full description of "tidy up song" project

src/en/news/blog/2024/cephalocon24-tshirt-contest/index.md
Repair the broken image link so that the image associated with the "Cephalocon 2024 Shirt Design Competition" link on en/news/blog renders as intended.
=> Repair image link on 2024 shirt design blog

src/en/community/events/2024/ceph-developer-summit-tentacle/index.md
... from Monday to Tuesday, same time.  Note that this extends the CDS by one day.
=> src/en/community/events/2024/ceph-developer-summit-tentacle: move RBD session again

README.md
`README.md` was pointing to an old wp.com hosted image which is no longer present. Updated to point to the image located at `src/assets/bitmaps/Ceph_Logo_Standard_RGB_120411_fa.png`
=> Fix the Ceph logo on README

package-lock.json, package.json
This seems to fix the errors in handling jpegs that main had.  At first, a current version of npm with "npm audit fix" was tried, but the resultant packages.json/packages-lock.json was not compatible with the npm on the web build host.  This was done with the npm version on the web build host, 6.14.4, and made a smaller set of changes than the current version of npm does.
This is only a stopgap to get the site back online.  Someone who knows nodejs and javascript needs to help out with a real refresh.
=> update packages based on npm audit fix on the www build host

src/en/community/events/2025/ceph-days-almaden/index.md
The CFP is supposed to open on 2025-01-13, please do not merge this PR before this date.
=> events: update Ceph Days Silicon Valley 2025 CFP

src/en/developers/roadmap/index.md
As mentioned in the CSC weekly, adding some links to the roadmap page.
cc: @neha-ojha
=> roadmap: add links to github projects

src/en/developers/google-summer-of-code/index.md
Update dates according to 2025 timeline.
Add few projects:
1. teuthology on podman
2. smartmontools drivedb.h postprocessor
3. Public telemetry slice/dice of SMART data
4. the more the merrier
5. warm and fuzzy
Preview: https://gsoc-2025.ceph.io/en/developers/google-summer-of-code/
=> gsoc: update page for gsoc 2025

src/en/developers/index.html
This change updates the front page of Ceph/Developers with a working link for Ceph documentation. The current link brings back "404 Documentation page not found".
Credit goes to @laimis9133 in https://github.com/ceph/ceph.io/pull/839.
=> src/en/developers/index: update documentation link

src/en/news/blog/2025/rgw-tiering-enhancements-part1/index.md, src/en/news/blog/2025/rgw-tiering-enhancements-part2/index.md
Add information to Anthony D'Atri's recent blog post about IBM Storage Ceph Object Storage Tiering Enhancements about when the blog post was written, in order to future-proof the blog post.
=> doc: add date to blog post

src/en/foundation/join/index.md
This PR updates the contact email address on the [Join the Ceph Foundation](https://ceph.io/en/foundation/join/) page.​
Previous email: membership@linuxfoundation.org
Updated to: support@cephfoundation.org​
This change aligns with the current communication channels of the Ceph Foundation.
Fixes: [ceph/ceph.io#867](https://github.com/ceph/ceph.io/issues/867)
=> Update contact email on 'Join the Ceph Foundation' page to support@cephfoundation.org

src/en/developers/index.html
The "Ceph guides, tips, and tricks" section at the bottom of the Ceph Developers webpage contained two outdated links. These links were either inaccessible due to invalid SSL certificates or had moved to new locations.
Updated Links:
Ten essential Ceph commands → (https://blog.softiron.com/engineering/10-essential-ceph-commands-for-managing-any-cluster-at-any-scale/)
Top five mistakes to avoid → (https://s3.amazonaws.com/cdn-media.softiron.com/doc/SoftIron_Avoid+these+5+Common+DIY+Ceph+Mistakes.pdf)
This update ensures users can access the correct resources without broken links.
Fixes #842
=> Fix issue #842: Update obsolete links in Ceph guides section

src/en/news/blog/2025/rook-on-mac-with-docker/index.md
This blog describe the procedure to install MAC M1 with docker as driver
=> Blog: Rook Installation on MAC M1 with docker as driver

src/en/community/events/2025/ceph-days-london/index.md
Tom Byrne: I was just starting to write my slides, and noticed that both the title and abstract I had submitted both contained typos...
I was rushing to get them submitted so it's definitely my error, and it's not the end of the world, but if it's not too painful to get them amended on the [website]. I would really appreciate that.
Amended Title: Lightning Talk (LT): Learning opportunities from a 100PB, 8 year old Ceph cluster
Amended Abstract: As our largest cluster 'Echo' approaches its 9th year of storing scientific data for the LHC experiments, we reflect on the ups, downs, and interesting technical details of keeping a larger-than-normal Ceph cluster running for nearly a decade.
=> Update Tom Byrne Title and abstract

src/en/news/blog/2025/v17-2-9-quincy-released/index.md
Change three links from RST syntax to MD syntax.
Also fix 1 typo `releas` -> `release`.
=> Fix RST syntax and typo in 17.2.9 Release notes

src/en/community/jobs/jobs.json
The page https://ceph.io/en/community/jobs/ contains couple of links that are dead. This PR is removing the dead links.
=> Rm dead job links
