ceph/ceph.io

- ansible/README.rst
- ansible/roles/deploy/defaults/main.yml
- ansible/roles/deploy/tasks/main.yml
- ansible/roles/deploy/templates/site-nossl.j2
- ansible/roles/deploy/templates/site.j2
This will let us see a live/public view of $GIT_BRANCH.ceph.io when a branch is pushed.
> Support wildcard subdomains

- ansible/roles/deploy/tasks/main.yml
- ansible/roles/deploy/templates/site.j2
> deploy: Tweak nginx config to allow external images

- ansible/roles/deploy/defaults/main.yml
- ansible/roles/deploy/tasks/main.yml
- ansible/roles/deploy/templates/site.j2
Probably should have split this into multiple PRs but we're still in the "fast and loose" phase
> File permissions, fix the rsync command, support multiple languages

- src/_includes/layouts/case-study.njk
- src/css/component.tooltip.css
- src/css/main.css
- HTML and CSS for tooltip component
The tooltip, currently, only appears on the [case studies](https://projects.invisionapp.com/share/D8Z2N4X7U6J#/screens/433224558).
> HTML and CSS for tooltip component.

- src/en-GB/discover/customers/index.html
- src/en-GB/discover/customers/index.md
> Discover customers layout.

- src/en-GB/developers/roadmap/index.html
- src/en-GB/developers/roadmap/index.md
> Developers roadmap layout

- src/en-GB/developers/career-opportunities/index.html
- src/en-GB/developers/career-opportunities/index.md
- Developers career opportunities layout
> Developers careers layout.

- src/_data/i18n/index.js
- src/css/base.table.css
- src/en-GB/community/community.json
- src/en-GB/community/tech-talks/index.html
- Community tech talks layout
- Dictionary items
- Table CSS update
> Tech talks layout, dictionary items, table CSS update.

- ansible/roles/deploy/defaults/main.yml
> ansible: Add youtube to nginx CSP

- src/_includes/layouts/_base.njk
Corrected the favicon asset path as it was missing a folder.
> Favicon asset path.

- src/css/base.blockquote.css
- src/css/base.codeblock.css
- src/css/base.table.css
- src/css/main.css
- src/css/object.grid.css
- Blockquote
- Pre and Code
- Table
- Tweaks to Grid to prevent width blowout
> Additional richtext CSS.

- .eleventy.js
- package-lock.json
- package.json
- src/css/base.focus.css
- src/css/base.typography.css
- src/css/component.site-header.css
- src/css/object.section.css
- src/css/settings.sizes.css
- src/en/community/meetups/index.html
- src/en/community/team/index.html
- src/en/discover/benefits/index.html
- src/en/discover/technology/index.html
- src/en/users/getting-started/index.html
- Installed markdown-it
- Installed markdown-it-anchor
- CSS for .richtext .link-anchor
Closes #121
> Markdown heading anchors

- .eleventy.js
- README.md
- src/_11ty/shortcodes/YouTube.js
- src/css/object.aspect-ratio.css
- src/en/community/tech-talks/index.html
- YouTube shortcode with props for id and title
- wrapped with aspect-ratio to make it responsive
- .richtext .aspect-ratio CSS
Closes #119
> YouTube Shortcode

- ansible/roles/deploy/templates/site.j2
Fixes: https://github.com/ceph/ceph.io/issues/103
> ansible: Configure nginx for 404s

- src/en/community/events/categories.html
- src/en/discover/case-studies/categories.html
- src/en/news/blog/categories.html
- src/en/news/blog/search.html
- src/en/news/press-releases/categories.html
> Removed pages from collections

- src/en/community/connect/index.html
- src/en/developers/code/index.html
- src/en/developers/contribute/index.html
- src/en/developers/index.html
- src/en/users/index.html
- Fixed some minor layout issues related to additional content added to the site
> Layout updates

- src/en/discover/technology/index.html
This is the first in a series of PRs that will
rewrite the "Discover -> Technology" page. This
page adds meaningful text and links to documentation
that more completely explains the components referred
to on this page.
Lorem ipsum text remains present here. When the technical
content added in this PR is approved, I'll ask Pete to remove
the lorem ipsum text.
> doc/ceph.io: discover -> technology (1 of x)

- ansible/roles/deploy/templates/site.j2
> ansible: Disable Japanese site for now

- src/en/foundation/about/index.md
First sections are cleaned up; later section changes are whitespace
only.
> foundation/about: update copy

- package-lock.json
- package.json
- postcss.config.js
- npm postcss-purgecss
- configured to look at .html, .njk, .js
- regex for defaultExtractor and safelist
Closes #138
> CSS optimisation

- src/_includes/layouts/listing-event-categories.njk
- src/en/community/connect/index.html
- src/en/community/meetups/index.html
Remove filler text and add the Ceph dev mailing list.
> Update Community pages

- src/en/foundation/index.html
Update 2 x H2 titles on Foundation page
> Minor title changes

- src/en/developers/index.html
Addresses #208 by replacing all lorem ipsum text with resources for developers and blurbs on community features.
> Doc/208 - Replacement of all lorem ipsum on developers page

- src/_includes/layouts/case-study.njk
Resolves #213 by replacing all lorem ipsum in use case 'discover more' modules with blurbs on Ceph's benefits, use cases, and case studies.
> Replaces case study 'Discover more' module lorem ipsum with real content

- src/_includes/layouts/case-study.njk
- src/_includes/layouts/listing-case-studies.njk
- src/en/community/connect/index.html
- src/en/users/documentation/index.html
- Layout fixes for `/community/connect` and `/users/documentation`
Closes #189
> Removed case study sponsor content when there is no sponsor

- ansible/roles/deploy/templates/redirects.j2
- ansible/roles/deploy/templates/site.j2
> ansible: Add redirects to nginx config

- src/_includes/layouts/_base.njk
Testing font loading strategies to improve performance metrics
> Font loading optimisations

- src/_includes/layouts/_base.njk
- src/css/settings.colors.css
- src/src.json
- meta description
- full site URL for hreflang
Closes #176
> SEO improvements

- src/en/community/events/2019/ceph-day-poland/index.md
- src/en/community/events/2019/cephalocon-barcelona/index.md
- src/en/news/publications/index.md
> Update some broken links

- src/en/news/blog/2021/v14-2-22-nautilus-released/index.md
> doc/releases: 14.2.22 Release Notes

- src/en/news/blog/2021/v16-2-5-pacific-released/index.md
> blog: 16.2.5 Release Notes

- src/en/foundation/members/index.md
Signed-off-by: Sage Weil <sage@newdream.net>
> foundation: remove didi

- src/en/news/blog/2021/v15-2-14-octopus-released/index.md
> v15.2.14 release notes

- src/en/users/telemetry/device-telemetry/index.html
- src/en/users/users.json
> users/telemetry: add device telemetry page

- ansible/roles/deploy/defaults/main.yml
- src/_includes/layouts/_base.njk
Signed-off-by: Sage Weil <sage@newdream.net>
> src/_includes/layouts/_base: add motomo tracking

- src/en/community/team/index.html
Missing a few bios.
Signed-off-by: Sage Weil <sage@newdream.net>
> community/team: update

- src/en/news/publications/index.md
Missed one in the previous commit.
> Fix broken asset link

- src/en/news/blog/2021/pacific-configuration-checks/index.md
Post that describes how to use the configuration check
feature introduced in Pacific
Signed-off-by: Paul Cuzner <pcuzner@redhat.com>
> blog:pacific configuration checker feature

- src/en/users/users.json
> users/telemetry: add 21/08 raw device data

- src/en/news/blog/2021/pacific-cli-monitoring/index.md
Post looking at a POC utility that exploits the data that
mgr/prometheus provides
Signed-off-by: Paul Cuzner <pcuzner@redhat.com>
> blog:cli monitoring with cmon

- src/en/news/blog/2021/v16-2-6-octopus-released/index.md
> doc/releases: 16.2.6 Release Notes

- src/en/news/blog/2021/v16-2-6-pacific-released/index.md
> blog: Remove breaklinks and replace . with (&#46;)

- src/en/community/meetups/index.html
This also adds in the community calender.
> Renaming Community meetings to virtual meetings

- src/en/news/blog/2021/v16-2-6-pacific-released/index.md
> blog: typo

- src/en/users/users.json
> users/telemetry: add raw device data links

- src/en/news/blog/2021/v16-2-7-pacific-released/index.md
> doc/releases: 16.2.7 Release Notes

- src/en/community/connect/index.html
Signed-off-by: Sebastian Wagner <sewagner@redhat.com>
> Fix #ceph-orchestrators IRC channel

- src/en/news/blog/2021/cephalocon-2022-cfp-now-open/index.md
> news/blog: Cephalocon CFP extension

- src/en/users/users.json
> users/telemetry: add 21/11 raw device data

- ansible/roles/deploy/defaults/main.yml
- src/en/community/meetups/index.html
- I believe this is the correct iframe `src` for Ceph Community Calendar (@Thingee to confirm)
- Minor styling: Full-width, and margins
- Fix unlinked "Virtual meetings" jumplink
Fixes #297
> Update Community Calendar embed

- src/en/foundation/members/index.md
Signed-off-by: Neha Ojha <nojha@redhat.com>
> foundation/members/index.md: qct is no longer a member

- src/en/users/users.json
> users/telemetry: add 21/12 raw device data

- src/en/security/index.md
> security: typo

- ansible/roles/deploy/templates/redirects.j2
Fixes: https://github.com/ceph/ceph.io/issues/334
> deploy: Serve images in community->en/news redirects

- src/en/developers/google-summer-of-code/index.md
Signed-off-by: Ali Maredia <amaredia@redhat.com>
>  developers/google-summer-of-code: Add mentor to dashboard project

- src/en/community/jobs/jobs.json
- Correct SUSE job listing company name
- Add SoftIron jobs
> community/jobs: Add SoftIron jobs

- src/en/community/meetups/index.html
> community/meetups: Add Marketing WG and User + Dev

- src/en/news/blog/2022/v15-2-16-octopus-released/index.md
Signed-off-by: Adam Kraitman <akraitma@redhat.com>
> doc/releases: 15.2.16 Release Notes

- ansible/roles/deploy/templates/site.j2
- src/_includes/layouts/_base.njk
> Set base href on 404 page

- src/en/users/users.json
> users/telemetry: add 22/01,02 raw device data

- src/en/foundation/members/index.md
> Updating Foundation member list for March

- src/en/community/community.json
> community/: Add new upcoming March 2022 tech talk!

- src/en/community/jobs/jobs.json
Added couple of Hitachi Vantara for job posting
> Added couple of Hitachi Vantara for job posting

- src/en/news/blog/2022/newsletter-april/index.md
> news/blog: Adding April community newsletter

- src/en/news/blog/2022/v17-2-0-quincy-released/index.md
> doc: 17.2.0 Release Notes

- src/en/news/blog/2022/v17-2-0-quincy-released/index.md
There is also a content section to link to various sections of the post.
> news/blog: Adding contributors to Quincy release post

- src/en/community/community.json
> community/tech-talk: Adding Telemetry Dashboard to the schedule

- src/en/community/jobs/jobs.json
This adds the "Cloud Storage Engineer" job position at Koor Technologies, Inc. to the jobs page.
> community/jobs: add Koor job position

- src/en/news/blog/2022/v16-2-8-pacific-released/index.md
> 16.2.8 Release notes

- src/en/news/blog/2022/v17-2-0-quincy-released/index.md
> news/blog: Update Quincy names in release notes

- src/en/news/blog/2022/v16-2-9-pacific-released/index.md
> 16.2.9 Release notes

- src/en/community/meetups/index.html
> community/meetups: Update meeting event times

- src/en/news/blog/2022/autoscaler_tuning/index.md
Signed-off-by: Laura Flores <lflores@redhat.com>
> en/news/blog/2022/autoscaler_tuning: add blog post about autoscaler tuning recommendations

- src/en/users/users.json
> users/telemetry: add 22/03-05 raw device data

- src/en/community/events/2022/cephalocon-portland/index.md
> community/events: Postpone Cephalocon 2022 again

- src/en/news/blog/2022/cephalocon-postponed-again/index.md
> news/blog: Cephalocon postponed again post

- src/en/community/events/2022/cephalocon-portland/index.md
> news/blog: Remove register button from cephalocon

- src/en/news/blog/2022/v17-2-1-quincy-released/index.md
> doc/releases: 17.2.1 Release Notes

- src/en/news/blog/2022/v17-2-1-quincy-released/index.md
> blog: Quincy not Pacific

- src/en/community/team/index.html
Signed-off-by: Samuel Just <sjust@redhat.com>
> community/team: add Yingxin Cheng as Seastore component lead

- src/en/community/jobs/jobs.json
updating with current open req situation.
> Remove previous position add new position at godaddy

- src/en/news/blog/2022/scaletesting-with-pawsey/index.md
Blog describing the testing done with Pawsey during the Quincy development cycle.
> news/blog: Pawsey scale testing

- src/en/users/index.html
Small correction of Get started to Getting started
> Gramatically updated the tech docs

- src/en/news/blog/2022/v16-2-10-pacific-released/index.md
- src/en/news/blog/2022/v17-2-2-quincy-released/index.md
> 17.2.2 and 16.2.10 Release Notes

- src/en/news/blog/2022/rocksdb-tuning-deep-dive/index.md
> news/blog: date update for rocks db post

- src/en/users/users.json
> users/telemetry: add 22/03-06 raw device data

- src/en/community/jobs/jobs.json
Add new engineering manager role at Canonical.
> Engineering Manager, Ceph & Distributed Storage

- src/en/news/blog/2022/v16-2-10-pacific-released/index.md
- src/en/news/blog/2022/v17-2-2-quincy-released/index.md
Signed-off-by: Seena Fallah <seenafallah@gmail.com>
> news: fix typo in v16.2.10 and v17.2.2 release

- src/en/news/blog/2022/v17-2-3-quincy-released/index.md
> 17.2.3 Release note

- src/en/users/users.json
> users/telemetry: add 22/07 raw device data

- src/en/community/events/2022/ceph-days-dublin/index.md
> community/events: Adding first Ceph Days Dublin Sponsor

- src/en/news/blog/2022/v15-2-17-octopus-released/index.md
> v15.2.17 release notes

- src/en/news/blog/2022/v15-2-17-octopus-released/index.md
Fix a typo and add a note for CVE-2022-0670.
Signed-off-by: Ilya Dryomov <idryomov@gmail.com>
> v15.2.17 release notes amendment

- src/en/community/ambassadors/index.html
Signed-off-by: Etienne Menguy <etienne.menguy@ubisoft.com>
> Update Etienne Menguy ambassador

- src/en/community/community.json
> community/tech-talks: Adding Vallari Agrawal for August

- src/en/community/events/2022/ceph-days-dublin/index.md
Correcting abstract information.
> commmunity/events: Updating Ceph Dublin schedule

- src/en/community/events/2022/ceph-days-dublin/index.md
> community/events: Adding Yaarit and Alexander's talk to Ceph Days Dublin

- src/en/news/blog/2022/v17-2-4-quincy-released/index.md
Signed-off-by: Yuri Weinstein <yweinste@redhat.com>
> 17.2.4 Release notes

- src/en/community/community.json
> community/tech-talk: adding october tech talk

- src/en/community/events/2022/ceph-virtual/index.md
> community/events: Adding Ceph Virtual 2022 event

- src/en/news/blog/2022/v17-2-5-quincy-released/index.md
Signed-off-by: Yuri Weinstein <yweinste@redhat.com>
> 17.2.5 Release notes

- src/en/community/events/2022/ceph-virtual/index.md
> community/events: Fix date in Ceph virtual schedule

- src/en/users/users.json
> users/telemetry: add 22/08 raw device data

- src/en/community/events/2022/ceph-virtual/index.md
The speaker's name for the DisTRaC talk is wrong. I know it's wrong as I am the one giving the talk.  
This pull request corrects the name of the speaker for said talk.
> Correcting the name of the speaker for DisTRaC talk

- src/en/community/events/2022/ceph-virtual/index.md
Signed-off-by: Josh Durgin <jdurgin@redhat.com>
> community/events: fix start date of ceph virtual

- src/en/community/team/index.html
community/team: add CLT team member Vikhyat Umrao
Signed-off-by: Vikhyat Umrao <vikhyat@redhat.com>
> community/team: add CLT team member Vikhyat Umrao

- src/en/community/events/2022/ceph-virtual/index.md
> community/events: Add Teletmetry talk to Virtual 2022

- src/en/community/events/2022/ceph-virtual/index.md
> community/events: Move Teletmetry talk to Nov 04

- src/en/community/jobs/jobs.json
add posting for Senior Storage SRE role at Akamai
> Senior Site Reliability Engineer - Storage

- src/en/community/events/2022/ceph-virtual/index.md
> communtiy/events: Update Crimson/Seastore scheduled talk

- src/en/news/blog/2022/ceph-use-case-survey-2022/index.md
Following the survey, a user reached out to me with more details about his use case. He asked if I could update the blog post with these details.
Signed-off-by: Laura Flores <lflores@redhat.com>
> ceph-use-case-survey-2022: update a use case with more details

- src/en/community/events/2022/ceph-virtual/index.md
> community/events: Add troubleshoot rook-ceph talk

- src/en/community/events/2022/ceph-virtual/index.md
> community/events: Remove Rook-Ceph Debug talk

- src/en/community/events/2023/ceph-days-nyc/index.md
> community/events: Add Ceph Days NYC event

- src/en/community/events/2023/ceph-days-nyc/index.md
> community/events: Registration information for CDNYC

- src/en/community/events/2023/ceph-days-nyc/index.md
> community/events: Add Ceph Days NYC registration link

- src/en/community/events/2023/ceph-days-socal/index.md
> community/events: Ceph Days Socal Date Correction

- src/en/news/blog/2022/centralized_logging/index.md
Fixed link to the dashboard configuration documentation.
Signed-off-by: Lenz Grimmer <lenz@grimmer.com>
> Centralized Logging on Ceph Dashboard: Fixed link

- src/en/news/blog/2023/v16-2-11-pacific-released/index.md
Signed-off-by: Yuri Weinstein <yweinste@redhat.com>
> 16.2.11 Release notes

- src/en/news/blog/2023/v16-2-11-pacific-released/index.md
Signed-off-by: Laura Flores <lflores@redhat.com>
> src/en/news/blog/2023/v16-2.11-pacific-released: fix PR list

- src/en/community/connect/index.html
Add Ceph's Slack to the "Connect" page.
Signed-off-by: Zac Dover <zac.dover@proton.me>
> en/community/connect: add Slack

- src/en/news/blog/2023/cephalocon-2023-amsterdam/index.md
> community/events: Fix Cephalocon 2023

- src/en/community/events/2023/cephalocon-amsterdam/index.md
> community/events: Fix Cephalocon 2023 event index page

- src/en/community/jobs/jobs.json
This removes all job postings that don't have valid links.
> Cleanup old job postings

- src/en/community/events/2023/ceph-days-socal/index.md
> community/events: Ceph Days SoCal CFP extended date

- src/en/community/events/2023/ceph-days-nyc/index.md
Signed-off-by: Danny Abukalam <danny@softiron.com>
> community/events: Correct typo in Sibench talk title

- src/en/community/events/2023/cephalocon-amsterdam/index.md
- src/en/news/blog/2023/cephalocon-2023-amsterdam/index.md
> community/events: fix Cephalocon 2023 dow typo

- src/en/community/events/2023/ceph-days-nyc/index.md
> community/events: fix Dan's photo for Ceph Day NYC

- src/en/developers/google-summer-of-code/index.md
Signed-off-by: Ali Maredia <amaredia@redhat.com>
> gsoc: remove old projects, add Coverity RGW project

- src/en/community/events/2023/ceph-days-nyc/index.md
Improve the grammar of the Ceph Days NYC 2023 page.
> community: grammar pass on Ceph Days NYC 2023

- src/en/community/connect/index.html
Solutions to join the Slack workspace are being researched at the moment. This will suffice for now.
> community/connect: Update Slack link

- src/en/community/events/2023/ceph-days-korea/index.md
> community/events: Adding Ceph Days Korea event page.

- src/en/community/events/2023/ceph-days-korea/index.md
Add a full stop to the end of a sentence that lacked it.
> ceph-days-korea/index.rst: add full stop

- src/en/community/events/2023/ceph-days-india/index.md
Updated the proposed dates for Ceph Days India.
> community/events: Adding Ceph Days India dates

- src/en/discover/index.html
> Fix typo "adaptability"

- src/en/community/jobs/jobs.json
Hello,
We have a job posting at Arm that may be of interest to Ceph folk.
Here's the job link.
Cheers,
Steve
> community/jobs: Staff Software Engineer - Storage

- src/en/community/events/2023/ceph-days-korea/index.md
Signed-off-by: Myoungwon Oh <myoungwon.oh@samsung.com>
> community/events: Update Ceph Days Korea Sponsor and Registration

- src/en/foundation/members/index.md
> foundation/members: Updating Foundation member page

- src/en/news/blog/2023/v17-2-6-quincy-released/index.md
> en/news/blog/2023/v17-2-6-quincy-released: fix osd entry

- src/en/community/connect/index.html
> community: refresh slack invite link

- src/en/community/events/2023/ceph-days-india/index.md
This is an update for Ceph Days India schedule.
> community/events: Update Ceph Days India schedule

- src/en/news/blog/2023/v16-2-12-pacific-released/index.md
> 16.2.12 Release notes

- src/en/community/meetups/index.html
- src/en/community/tech-talks/index.html
Also updating meeting info for weekly meetings, and switch calendar view to agenda.
> community/tech-talks: Update meeting info for tech talks

- src/en/community/ambassadors/index.html
> Correcting my name

- src/en/news/publications/index.md
Signed-off-by: Myoungwon Oh <myoungwon.oh@samsung.com>
> news/publication: Update accepted paper (TiDedup)

- src/en/community/community.json
Added slides link to the Tech Talk
> Added slides to Making Teuthology Friendly

- src/en/news/blog/2023/user-dev-meeting-relaunch/index.md
> src/en/news/blog/2023/user-dev-meeting-relaunch: add blog post about user + dev relaunch

- src/en/foundation/members/index.md
> foundation/members: update 26092023

- src/en/news/blog/2023/v18-2-1-reef-released/index.md
Followup to https://github.com/ceph/ceph.io/pull/626.
> en/news/blog/2023/v18-2-1-reef-released: specify dashboard improvements

- src/en/community/events/2024/cloudstack-and-ceph-day-netherlands/index.md
Joachim asked me to help fix the dates for this event from the 8th of Feb to the 22nd of Feb.  Needs a review from someone that knows more than I do about what's going on here. :)
> community/events: Fix Ceph Days Amsterdam 2024 Date

- src/en/developers/google-summer-of-code/index.md
Added a section in GSOC project regarding Teuthology/Build System project description
> src/en/developers/google-summer-of-code/index.md: Added Project

- src/en/community/team/index.html
Remove David Galloway from the Teams page.
> Remove D. Galloway from community/teams/index.html

- src/en/developers/google-summer-of-code/index.md
adding a ference to a gist holding the full description.
> gsoc: full description of RADOS to REDIS GSoC project

- src/en/community/events/2024/ceph-days-nyc/index.md
> events/2024: Extend Ceph Days NYC CFP Date

- src/en/community/events/2024/ceph-days-india/index.md
I added the CFP form for Ceph Days India 2024 event.
> community/events: Adding Ceph Days India 2024 CFP form

- src/en/community/events/2024/ceph-days-india/index.md
Added Ceph Day India 2024 registration & schedule
> community/events: Adding Ceph Days India 2024 schedule

- src/en/community/events/2024/user-dev-meeting/index.md
> remove tags and image on user + dev blog post

- src/en/community/events/2024/ceph-days-asia/index.md
Add an event for Ceph Days Asia 2024.
Signed-off-by: Sungmin Lee sung_min.lee@samsung.com
> community/events: Adding Ceph Days Asia 2024 event page

- src/en/community/team/index.html
Add Casey Cain as the Community team member.
> community/team: add Casey Cain

- src/en/community/team/index.html
Add Matan Breizman as the Crimson team lead.
> community/team: Add Matan Breizman

- src/en/community/jobs/jobs.json
> Remove GoDaddy posting

- src/en/users/getting-started/index.html
Link was broken by: https://github.com/ceph/ceph/commit/74cc624d002e51769da37c04b3bdc32e0077d370
> Update index.html to update intro link

- src/en/community/events/2024/ceph-days-london/index.md
> Ceph Days London: fix image aspect ratio

- src/en/community/events/2024/ceph-days-asia/index.md
This PR includes followings.
- Adding Ceph Days Asia 2024 schedule
- Closing CFP
- Updating important days
> community/events: Improving Ceph Days Asia 2024 page

- src/en/community/ambassadors/index.html
This is an update for the Ceph Community Ambassadors program
> community/ambassadors: Updating the Community Ambassador program

- src/en/news/blog/2024/v18-2-4-reef-released/index.md
> s/avoidfurther/avoid further/

- src/en/community/events/2024/ceph-days-asia/index.md
Update schedule for adding a keynote session and removing dropped sessions.
Signed-off-by: Sungmin Lee sung_min.lee@samsung.com
> community/events: Udpate Ceph Days Asia 2024 schedule

- src/en/community/team/index.html
update rgw leaders in https://ceph.io/en/community/team/
> team: update rgw component leads

- src/en/foundation/members/index.md
Remove Koor from membership due to business closure.
> Remove Koor from membership due to business closure

- src/en/news/blog/2025/automating-ceph-cluster-deployments_part1/index.md
Originally proposed by @R0gue-one on GitHub: https://github.com/ceph/ceph.io/pull/798
Resovles Issue #787.
> src/en/news/blog/2025/automating-ceph-cluster-deployments_part1: fix typo

- src/en/news/blog/2025/rbd-live-migration/index.md
https://github.com/anthonyeleven/ceph.io/pull/new/rbd-live-migration2
Signed-off-by: Anthony D'Atri <anthonyeleven@users.noreply.github.com>
> Crosspost RBD live migration article from the IBM community

- src/en/developers/google-summer-of-code/index.md
And rename "intermediate" difficulity level to "medium" to follow easy/medium/hard pattern.
> gsoc: Add dashboard project

- src/en/community/jobs/jobs.json
Add an advertisment for a job opening for a Senior Software Engineer at Hetzner Cloud.
> community/jobs: add Hetzner job

- src/en/community/jobs/jobs.json
Removing job posting where the job links are no longer valid
> Remove dead links for job postings

- src/en/developers/google-summer-of-code/index.md
And spell check.
Preview: https://gsoc-more-the-merrier.ceph.io/en/developers/google-summer-of-code/
> gsoc: Add project desc link to "The More the Merrier"

- src/en/developers/google-summer-of-code/index.md
To project "warm and fuzzy" on Yuval's request.
> gsoc: add Pritha as co-mentor

- src/en/community/events/2025/ceph-days-almaden/index.md
Updated Cephadm title and abstract
> Ceph Days Silicon Valley: Cephadm update

- src/en/developers/google-summer-of-code/index.md
> take out SMART slice/dice from GSOC

- src/en/community/jobs/jobs.json
Hi, we'd be delighted if you could add this to your job posting list.
> Update jobs.json - adding Boson AI's job post

- src/en/developers/google-summer-of-code/index.md
- adds a link to the gist, handy for updates and useful information for contributors
- corrects a typo
> gsoc: Add link to detailed description of dashboard

- src/en/community/events/2025/ceph-day-seattle/index.md
clean up CD Seattle and goose site build
CD Seattle is not being picked up by the site build, attempt to remedy that.
> clean up CD Seattle and goose site build

- src/en/news/blog/2025/stretch-cluuuuuuuuusters-part1/index.md
- src/en/news/blog/2025/stretch-cluuuuuuuuusters-part2/index.md
- src/en/news/blog/2025/stretch-cluuuuuuuuusters-part3/index.md
Fix image for stretch cluster post
> Fix image for stretch cluster post

- src/en/community/jobs/jobs.json
> community/jobs: add new walmart job posting

- src/en/community/events/2025/ceph-days-almaden/index.md
Adding the links to the slides for Ceph Day Silicon Valley
> Add links to slides for CD SV

- src/en/community/events/2025/ceph-day-seattle/index.md
> update CD Seattle schedule

- src/en/news/blog/2025/rook-on-mac-with-docker/index.md
> Update Date in the Blog for Rook On MAC M1 index.md

- src/en/community/ambassadors/index.html
I've recently transitioned professionally, leaving my university to join Clyso. This commit updates my biography accordingly.
> New position

- src/en/community/events/2025/cephalocon-2025/index.md
- src/en/community/events/2025/new-users-workshop-2025/index.md
Added venue and address to the Cephalocon event page
> Wip michelle 2

- src/en/foundation/members/index.md
Reflect Clyso Upgrade To Diamond
> Reflect Clyso Upgrade To Diamond

- src/en/news/blog/2025/cephalocon-blog/index.md
> Fixing photo on blog post for Cephalocon

- src/en/news/blog/2025/benchmarking-object-part1/index.md
- src/en/news/blog/2025/benchmarking-object-part2/index.md
Fix 2025/benchmarking-object links
> Fix 2025/benchmarking-object links
